export interface IVehicleRequest {
    ID: any,
    Created: any,
    Title: any,
    EmployeeID: any,
    EmployeeName: any,
    Status: any,
    EmployeeType: any,
    Designation: any,
    Age: any,
    EmployeeCode: any,
    DateOfJoining: any,
    ResidenceAddress: any,
    TotalEmoluments: any,
    Emoluments25: any,
    TotalDeductions: any,
    NetEmoluments50: any,
    EmiTenure: any,
    VehicleType: any,
    VehicleCondition: any,
    MakeModel: any,
    ManufactureYear: any,
    CostOfVehicle: any,
    ExpectedLife: any,
    SellerDetails: any,
    PrevVehicleLoanType: any,
    PrevLoanAmount: any,
    PrevLoanDate: any,
    PrevLoanRepaymentDate: any,
    ConfirmedDate: any,
    EmiRepaymentAmount: any,
    VehicleLoanCost: any,
    WithdrawalDetails: any,
    WithdrawalAmount: any,
    OutstandingLoan: any,
    FinalRepaymentDate: any,
    AmountofLoanAvailed: any,
    DateofLoanAvailed: any,
    DateOfConfirmation:any,
    SanctionAmountDate:any,
    HR1Response	:any,	
    HR1Remark:any,
    HR2Response:any,
    HR2Remark:any,
    GHResponse:any,
    GHRemark:any,
    IsConfirm	:any,
    TotalMarks:any,
    IsEmiLessThan50: any,
    VehicleLoanEMI:any,
    EligibleLoanAmount: any,
    ApplicationCorrect: any,
    DisciplinaryProceedings:any,
    SanctionAmount		: any,
}
